---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git
  pull: default
  image: plugins/git:next
  settings:
    depth: 50
    tags: true

- name: test
  pull: default
  image: golang:1.16
  environment:
    GO111MODULE: on
    GOPROXY: https://goproxy.cn
  commands:
    - go build -v
    - go vet ./...
    - go test -v -race -coverprofile=coverage.txt -covermode=atomic
  when:
    event:
    - push
    - pull_request

- name: upload
  image: covergates/drone-covergates
  settings:
    report_id: bt0k07q23akg00ac0fv0
    report: coverage.txt
    type: lcov